
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app_container
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/pokemon_db"
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
